replace `pb_media_attribution_title` with the existing 'title' field
BCcampus/pressbooks pull request #27
Opened 2018-07-17 21:49 UTC by alex-418

Completes https://github.com/BCcampus/pressbooks/issues/24

2018-07-17 22:08 UTC, bdolor requested changes
there are a lot of formatting changes that were made to `inc/posttype/namespace.php` that has generated numerous errors. 

![image](https://user-images.githubusercontent.com/2048170/42848142-2bf50218-89d3-11e8-870f-916f4bef465e.png)

2018-07-17 22:25 UTC, bdolor commented
this will also need to reconcile removing the input field for `pb_media_attribution_title`, but keeping `register_meta` and not providing an alternative to updating the saving of `pb_media_attribution_title`. 

Question - in `save_metadata_attachment()` should we be saving the value of `get_the_title()` to `pb_media_attribution_title` or should we remove `pb_media_attribution_title` from `register_meta`?

2018-07-17 22:44 UTC, alex-418 commented
I've removed `pb_media_attribution_title` from register_meta, as per our initial thoughts in https://github.com/BCcampus/pressbooks/issues/24 ... but I'm thinking for consistency it would make sense to save the value of `get_the_title()` and add it to `register_meta` like the others, since it'd be expected to appear there ?

2018-07-18 20:38 UTC, bdolor approved these changes

2018-07-18 20:38 UTC, merged